
(function(){"use strict";
var DB_NAME="VokabeltrainerTest",DB_VERSION=1,STORE_VOCAB="vocab",STORE_PROGRESS="progress",db=null,vocab=[],index=0,direction="DE_FR",autoTimer=null;
var seed=[{id:"le-projet",courseId:"franzoesisch",unitId:"unite-1",foreign:"le projet",meanings:["der Plan","das Vorhaben","das Projekt"]},{id:"le-metier",courseId:"franzoesisch",unitId:"unite-1",foreign:"le métier",meanings:["der Beruf"]},{id:"le-domaine",courseId:"franzoesisch",unitId:"unite-1",foreign:"le domaine",meanings:["das Gebiet","der Bereich"]}];
function $(id){return document.getElementById(id)}
function reqPromise(req){return new Promise(function(resolve,reject){req.onsuccess=function(){resolve(req.result)};req.onerror=function(){reject(req.error)}})}
function openDb(){return new Promise(function(resolve,reject){var req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=function(e){var d=e.target.result;if(!d.objectStoreNames.contains(STORE_VOCAB))d.createObjectStore(STORE_VOCAB,{keyPath:"id"});if(!d.objectStoreNames.contains(STORE_PROGRESS))d.createObjectStore(STORE_PROGRESS,{keyPath:"id"})};req.onsuccess=function(){resolve(req.result)};req.onerror=function(){reject(req.error)}})}
function store(name,mode){return db.transaction(name,mode||"readonly").objectStore(name)}
async function seedIfNeeded(){var count=await reqPromise(store(STORE_VOCAB).count());if(count===0){var tx=db.transaction(STORE_VOCAB,"readwrite"),s=tx.objectStore(STORE_VOCAB);seed.forEach(function(v){s.put(v)});await new Promise(function(res,rej){tx.oncomplete=res;tx.onerror=function(){rej(tx.error)}})}}
async function loadVocab(){vocab=await reqPromise(store(STORE_VOCAB).getAll());vocab.sort(function(a,b){return a.foreign.localeCompare(b.foreign,"fr")});if(index>=vocab.length)index=0}
function normalizeProgress(p,id){p=p||{};return{id:id,deFr:Number(p.deFr||0),frDe:Number(p.frDe||0),attempts:Number(p.attempts||0),correct:Number(p.correct||0),almost:Number(p.almost||0),wrong:Number(p.wrong||0),attemptsDEFR:Number(p.attemptsDEFR||0),attemptsFRDE:Number(p.attemptsFRDE||0),lastPracticedAt:p.lastPracticedAt||null}}
async function getProgress(id){return normalizeProgress(await reqPromise(store(STORE_PROGRESS).get(id)),id)}
async function saveProgress(p){await reqPromise(store(STORE_PROGRESS,"readwrite").put(p))}
function norm(s){return String(s||"").trim().toLowerCase().replace(/[’‘`´]/g,"'").replace(/\s+/g," ")}
function stripAccents(s){try{return norm(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"")}catch(e){return norm(s)}}
function germanAccepted(item,given){var g=norm(given),gNo=g.replace(/^(der|die|das|ein|eine|einen|einem|einer)\s+/,"");for(var i=0;i<item.meanings.length;i++){var x=norm(item.meanings[i]),xNo=x.replace(/^(der|die|das|ein|eine|einen|einem|einer)\s+/,"");if(g===x||gNo===xNo)return true}return false}
function keepAnswerFocused(){var a=$("answer");try{a.focus({preventScroll:true})}catch(e){a.focus()}}
async function renderCard(resetFeedback){if(vocab.length===0){$("prompt").textContent="Keine Vokabeln vorhanden";return}var item=vocab[index],p=await getProgress(item.id);$("progress").textContent=(index+1)+" / "+vocab.length;$("direction").textContent=direction==="DE_FR"?"Deutsch → Französisch":"Französisch → Deutsch";$("prompt").textContent=direction==="DE_FR"?item.meanings.join(" / "):item.foreign;$("level").textContent="Lernstufe "+(direction==="DE_FR"?p.deFr:p.frDe);$("languageHint").textContent=direction==="DE_FR"?"Französisch schreiben – Scribble einmal auf Französisch stellen.":"Deutsch schreiben – Scribble/Diktat auf Deutsch stellen.";$("answer").lang=direction==="DE_FR"?"fr":"de";$("answer").value="";$("answer").placeholder=direction==="DE_FR"?"Französisch mit Apple Pencil schreiben oder diktieren …":"Deutsch mit Apple Pencil schreiben oder diktieren …";if(resetFeedback!==false){$("feedback").className="feedback";$("feedback").textContent="Noch keine Antwort geprüft."}setTimeout(keepAnswerFocused,40)}
async function check(){if(autoTimer){clearTimeout(autoTimer);autoTimer=null}var item=vocab[index],given=norm($("answer").value),feedback=$("feedback");if(!given){feedback.className="feedback almost";feedback.textContent="Bitte zuerst eine Antwort eingeben.";keepAnswerFocused();return}var p=await getProgress(item.id),correct=false;p.attempts++;p.lastPracticedAt=new Date().toISOString();if(direction==="DE_FR")p.attemptsDEFR++;else p.attemptsFRDE++;if(direction==="DE_FR"){var wanted=norm(item.foreign);if(given===wanted){correct=true;p.deFr=Math.min(5,p.deFr+1);p.correct++;feedback.className="feedback good";feedback.innerHTML="✓ Richtig: <strong>"+item.foreign+"</strong><br>Die Lernstufe wurde erhöht."}else if(stripAccents(given)===stripAccents(wanted)){p.almost++;feedback.className="feedback almost";feedback.innerHTML="Fast richtig – Akzent oder Sonderzeichen prüfen.<br>Richtig: <strong>"+item.foreign+"</strong>"}else{p.deFr=Math.max(0,p.deFr-1);p.wrong++;feedback.className="feedback bad";feedback.innerHTML="✗ Noch nicht richtig.<br>Richtig: <strong>"+item.foreign+"</strong>"}}else{if(germanAccepted(item,given)){correct=true;p.frDe=Math.min(5,p.frDe+1);p.correct++;feedback.className="feedback good";feedback.innerHTML="✓ Richtig: <strong>"+item.meanings.join(" / ")+"</strong><br>Die Lernstufe wurde erhöht."}else{p.frDe=Math.max(0,p.frDe-1);p.wrong++;feedback.className="feedback bad";feedback.innerHTML="✗ Noch nicht richtig.<br>Richtig: <strong>"+item.meanings.join(" / ")+"</strong>"}}await saveProgress(p);$("level").textContent="Lernstufe "+(direction==="DE_FR"?p.deFr:p.frDe);await renderOverview();keepAnswerFocused();if(correct&&$("autoNext").checked){autoTimer=setTimeout(async function(){index=(index+1)%vocab.length;await renderCard(true)},900)}}
async function nextCard(){if(autoTimer){clearTimeout(autoTimer);autoTimer=null}index=(index+1)%vocab.length;await renderCard(true)}
async function switchDirection(){if(autoTimer){clearTimeout(autoTimer);autoTimer=null}direction=direction==="DE_FR"?"FR_DE":"DE_FR";await renderCard(true)}
function fmtDate(iso){if(!iso)return"–";try{return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(iso))}catch(e){return"–"}}
async function renderOverview(){var body=$("overviewBody");body.innerHTML="";var totals={attempts:0,correct:0,almost:0,wrong:0};for(var i=0;i<vocab.length;i++){var item=vocab[i],p=await getProgress(item.id);totals.attempts+=p.attempts;totals.correct+=p.correct;totals.almost+=p.almost;totals.wrong+=p.wrong;var tr=document.createElement("tr"),vals=[item.foreign+" — "+item.meanings.join(" / "),"Stufe "+p.deFr+" ("+p.attemptsDEFR+"×)","Stufe "+p.frDe+" ("+p.attemptsFRDE+"×)",String(p.attempts),String(p.correct),String(p.almost),String(p.wrong),fmtDate(p.lastPracticedAt)];vals.forEach(function(v,idx){var td=document.createElement("td");if(idx===1||idx===2){var span=document.createElement("span");span.className="level-pill";span.textContent=v;td.appendChild(span)}else td.textContent=v;tr.appendChild(td)});body.appendChild(tr)}$("sumAttempts").textContent=totals.attempts;$("sumCorrect").textContent=totals.correct;$("sumAlmost").textContent=totals.almost;$("sumWrong").textContent=totals.wrong}
function showView(which){$("learnView").hidden=which!=="learn";$("overviewView").hidden=which!=="overview";$("dataView").hidden=which!=="data";$("tabLearn").classList.toggle("active",which==="learn");$("tabOverview").classList.toggle("active",which==="overview");$("tabData").classList.toggle("active",which==="data");if(which==="learn")setTimeout(keepAnswerFocused,50);if(which==="overview")renderOverview()}
async function importJson(file){var data=JSON.parse(await file.text());if(!Array.isArray(data.entries))throw new Error("Die Datei enthält kein entries-Array.");var tx=db.transaction(STORE_VOCAB,"readwrite"),s=tx.objectStore(STORE_VOCAB),count=0;data.entries.forEach(function(e){if(!e.id||!e.foreign||!Array.isArray(e.meanings)||!e.meanings.length)return;s.put({id:String(e.id),courseId:(data.course&&data.course.id)||e.courseId||"import",unitId:(data.unit&&data.unit.id)||e.unitId||"import",foreign:String(e.foreign),meanings:e.meanings.map(String)});count++});await new Promise(function(res,rej){tx.oncomplete=res;tx.onerror=function(){rej(tx.error)}});await loadVocab();$("importResult").textContent=count+" Vokabel(n) importiert/aktualisiert.";await renderCard(true)}
async function exportBackup(){var entries=await reqPromise(store(STORE_VOCAB).getAll()),progress=await reqPromise(store(STORE_PROGRESS).getAll()),data={schemaVersion:2,exportedAt:new Date().toISOString(),entries:entries,progress:progress},blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="vokabeltrainer-backup.json";document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},1000)}
async function resetAll(){if(!confirm("Alle Testdaten und Lernstände löschen?"))return;await reqPromise(store(STORE_VOCAB,"readwrite").clear());await reqPromise(store(STORE_PROGRESS,"readwrite").clear());await seedIfNeeded();await loadVocab();index=0;direction="DE_FR";await renderCard(true);await renderOverview()}
$("check").addEventListener("pointerdown",function(e){e.preventDefault()});$("next").addEventListener("pointerdown",function(e){e.preventDefault()});$("check").addEventListener("click",check);$("next").addEventListener("click",nextCard);$("switch").addEventListener("click",switchDirection);$("tabLearn").addEventListener("click",function(){showView("learn")});$("tabOverview").addEventListener("click",function(){showView("overview")});$("tabData").addEventListener("click",function(){showView("data")});$("refreshOverview").addEventListener("click",renderOverview);$("export").addEventListener("click",exportBackup);$("reset").addEventListener("click",resetAll);$("jsonFile").addEventListener("change",async function(e){var f=e.target.files&&e.target.files[0];if(!f)return;try{await importJson(f)}catch(err){$("importResult").textContent="Importfehler: "+err.message}e.target.value=""});
(async function init(){try{db=await openDb();await seedIfNeeded();await loadVocab();await renderCard(true);await renderOverview();$("appStatus").textContent="✓ JavaScript läuft. IndexedDB ist verfügbar. Version 2 geladen."}catch(err){$("appStatus").textContent="Fehler beim Start: "+err.message;$("appStatus").style.background="#fdeaea"}})();
})();
if("serviceWorker" in navigator){window.addEventListener("load",function(){navigator.serviceWorker.register("./sw.js").catch(function(){})})}
